alias sz="source ~/.zshrc"
alias zrc="vi ~/.zshrc"
alias zalias="vi $ZSH_CUSTOM/aliases.zsh"
alias gs="git status"
alias gf="git fetch"
alias y="yarn"
alias ys="yarn start"
alias ylinks="( ls -l node_modules ; ls -l node_modules/@* ) | grep ^l"
